### PR TITLE
ci/cd: Update nightly-readme-build.yml

### LINKED ISSUE #28: ci/cd: fix automatic nightly knit of `README.md`
The knitting itself seems to function fine, and the action passes without complaining, but the action doesn't successfully commit and push the changes. 

Relates to https://github.com/RMI-PACTA/pacta.sit.rep/actions/workflows/nightly-readme-build.yml

Screenshot 2024-05-02 at 17 34 27

### PR DESCRIPTION
**Pull request by jdhoffa**
Use GH action to build `README.Rmd` and commit it to a new PR (as opposed to pushing directly to `main`). 

Sorry @cjyetman for the back-to-back GH action PRs here. It's difficult to test these without merging them in. 

Maybe closes #28

### CODE REVIEW

**Comment by cjyetman** [comment]
As usual, I don't quite understand why this README needs to be dynamic, e.g.

| Repo          | Lifecycle     | Status     | Test_Coverage  | Latest_SHA   | Maintainer |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| [pacta.portfolio.utils](https://github.com/RMI-PACTA/pacta.portfolio.utils)                     | [Lifecycle](https://lifecycle.r-lib.org/articles/stages.html)  | [R-CMD-check](https://github.com/RMI-PACTA/pacta.portfolio.utils/actions/workflows/R-CMD-check.yaml) | [Codecov test coverage](https://app.codecov.io/gh/RMI-PACTA/pacta.portfolio.utils?branch=main)                     | [last commit](https://github.com/RMI-PACTA/pacta.portfolio.utils/commits/main/) | [@cjyetman](https://github.com/cjyetman/) |

**Comment by jdhoffa** [comment]
Repo would never need to be updated. 
R CMD check status and Test coverage badges also don't need to be updated as they don't need to point anywhere else. 

But Lifecycle and Maintainer need to be dynamic

**Comment by jdhoffa** [comment]
Cool tip with the latest commit SHA badge though! Gonna consider adding that

**Comment by jdhoffa** [comment]
If there's a way to automatically update those values in a standard README.md then I'm all for it, but this was the simplest way I could think of. ¯\_(ツ)_/¯

**Review by cjyetman — APPROVED** [review]

**Comment by jdhoffa** [comment]
That's awesome!!

**Comment by jdhoffa** [comment]
So the lifecycle badge is the only straggler now XD

**Comment by cjyetman** [comment]
> So the lifecycle badge is the only straggler now XD

yeah, that one is tough because they're so standard way of defining it that GitHub's API understands 🤷🏻

**Comment by cjyetman** [comment]
https://api.github.com/repos/rmi-pacta/pacta.portfolio.utils/contents/README.md
``` json
{
  "name": "README.md",
  "path": "README.md",
  "sha": "509c2e2a4aba215c8294e3579e7fdcfad0a85158",
  "size": 1622,
  "url": "https://api.github.com/repos/RMI-PACTA/pacta.portfolio.utils/contents/README.md?ref=main",
  "html_url": "https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/main/README.md",
  "git_url": "https://api.github.com/repos/RMI-PACTA/pacta.portfolio.utils/git/blobs/509c2e2a4aba215c8294e3579e7fdcfad0a85158",
  "download_url": "https://raw.githubusercontent.com/RMI-PACTA/pacta.portfolio.utils/main/README.md",
  "type": "file",
  "content": "IyBwYWN0YS5wb3J0Zm9saW8udXRpbHMgPGltZyBzcmM9Im1hbi9maWd1cmVz\nL2xvZ28ucG5nIiBhbGlnbj0icmlnaHQiIHdpZHRoPSIxMjAiIC8+Cgo8IS0t\nIGJhZGdlczogc3RhcnQgLS0+ClshW0xpZmVjeWNsZTogc3RhYmxlXShodHRw\nczovL2ltZy5zaGllbGRzLmlvL2JhZGdlL2xpZmVjeWNsZS1zdGFibGUtYnJp\nZ2h0Z3JlZW4uc3ZnKV0oaHR0cHM6Ly9saWZlY3ljbGUuci1saWIub3JnL2Fy\ndGljbGVzL3N0YWdlcy5odG1sI3N0YWJsZSkKWyFbUi1DTUQtY2hlY2tdKGh0\ndHBzOi8vZ2l0aHViLmNvbS9STUktUEFDVEEvcGFjdGEucG9ydGZvbGlvLnV0\naWxzL2FjdGlvbnMvd29ya2Zsb3dzL1ItQ01ELWNoZWNrLnlhbWwvYmFkZ2Uu\nc3ZnKV0oaHR0cHM6Ly9naXRodWIuY29tL1JNSS1QQUNUQS9wYWN0YS5wb3J0\nZm9saW8udXRpbHMvYWN0aW9ucy93b3JrZmxvd3MvUi1DTUQtY2hlY2sueWFt\nbCkKWyFbY29kZWNvdl0oaHR0cHM6Ly9jb2RlY292LmlvL2doL1JNSS1QQUNU\nQS9wYWN0YS5wb3J0Zm9saW8udXRpbHMvZ3JhcGgvYmFkZ2Uuc3ZnKV0oaHR0\ncHM6Ly9jb2RlY292LmlvL2doL1JNSS1QQUNUQS9wYWN0YS5wb3J0Zm9saW8u\ndXRpbHMpClshW0NSQU4gc3RhdHVzXShodHRwczovL3d3dy5yLXBrZy5vcmcv\nYmFkZ2VzL3ZlcnNpb24vcGFjdGEucG9ydGZvbGlvLnV0aWxzKV0oaHR0cHM6\nLy9DUkFOLlItcHJvamVjdC5vcmcvcGFja2FnZT1wYWN0YS5wb3J0Zm9saW8u\ndXRpbHMpClshW3BhY3RhLnBvcnRmb2xpby51dGlscyBzdGF0dXMgYmFkZ2Vd\nKGh0dHBzOi8vcm1pLXBhY3RhLnItdW5pdmVyc2UuZGV2L2JhZGdlcy9wYWN0\nYS5wb3J0Zm9saW8udXRpbHMpXShodHRwczovL3JtaS1wYWN0YS5yLXVuaXZl\ncnNlLmRldi91aSNwYWNrYWdlOnBhY3RhLnBvcnRmb2xpby51dGlscykKPCEt\nLSBiYWRnZXM6IGVuZCAtLT4KClRoZSBnb2FsIG9mIHBhY3RhLnBvcnRmb2xp\nby51dGlscyBpcyB0byBwcm92aWRlIHV0aWxpdHkgZnVuY3Rpb25zIGZvciB0\naGUgUEFDVEEgZm9yIEludmVzdG9ycyB0b29scyBhbmQgZWNvc3lzdGVtLgoK\nIyMgSW5zdGFsbGF0aW9uCgo8IS0tCllvdSBjYW4gaW5zdGFsbCB0aGUgcmVs\nZWFzZWQgdmVyc2lvbiBvZiBwYWN0YS5wb3J0Zm9saW8udXRpbHMgZnJvbSBb\nQ1JBTl0oaHR0cHM6Ly9DUkFOLlItcHJvamVjdC5vcmcpIHdpdGg6CgpgYGAg\ncgppbnN0YWxsLnBhY2thZ2VzKCJwYWN0YS5wb3J0Zm9saW8udXRpbHMiKQpg\nYGAKLS0+CgpZb3UgY2FuIGluc3RhbGwgdGhlIGRldmVsb3BtZW50IHZlcnNp\nb24gb2YgcGFjdGEucG9ydGZvbGlvLnV0aWxzIGZyb20gW1ItdW5pdmVyc2Vd\nKGh0dHBzOi8vcm1pLXBhY3RhLnItdW5pdmVyc2UuZGV2L3BhY3RhLnBvcnRm\nb2xpby51dGlscykgd2l0aDoKCmBgYCByCmluc3RhbGwucGFja2FnZXMoInBh\nY3RhLnBvcnRmb2xpby51dGlscyIsIHJlcG9zID0gImh0dHBzOi8vcm1pLXBh\nY3RhLnItdW5pdmVyc2UuZGV2IikKYGBgCgpvciBmcm9tIFtHaXRIdWJdKGh0\ndHBzOi8vZ2l0aHViLmNvbS9STUktUEFDVEEvcGFjdGEucG9ydGZvbGlvLnV0\naWxzKSB3aXRoOgoKYGBgIHIKIyBpbnN0YWxsLnBhY2thZ2VzKCJwYWsiKQpw\nYWs6OnBhaygiUk1JLVBBQ1RBL3BhY3RhLnBvcnRmb2xpby51dGlscyIpCmBg\nYAo=\n",
  "encoding": "base64",
  "_links": {
    "self": "https://api.github.com/repos/RMI-PACTA/pacta.portfolio.utils/contents/README.md?ref=main",
    "git": "https://api.github.com/repos/RMI-PACTA/pacta.portfolio.utils/git/blobs/509c2e2a4aba215c8294e3579e7fdcfad0a85158",
    "html": "https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/main/README.md"
  }
}
```
and the content is base64 encoded

**Pull request merged**
